name: EoH
channels:
  - defaults
dependencies:
  - pandas
  - pip
  - pandas
  - requests
  - scikit-learn
  - ruptures
  - pydotplus
  - plotly-orca
  - plotly
  - numpy
  - matplotlib
  - tqdm
  - tk
  - zeromq
  - traitlets
  - debugpy
  - vs2015_runtime
  - pygments
  - wcwidth
  - psutil
  - jupyter_client
  - certifi
  - tzdata
  - decorator
  - zlib
  - pure_eval
  - tornado
  - parso
  - prompt-toolkit
  - entrypoints
  - ca-certificates
  - jedi
  - nest-asyncio
  - backcall
  - libsodium
  - jupyter_core
  - six
  - stack_data
  - matplotlib-inline
  - pickleshare
  - pywin32
  - python=3.10
  - libffi
  - pyzmq
  - colorama
  - packaging
  - python-dateutil
  - setuptools
  - xz
  - wheel
  - asttokens
  - vc
  - wincertstore
  - platformdirs
  - ipython
  - executing
  - comm
  - openssl
  - bzip2
  - sqlite
  - ipykernel
  - graphviz
