#!/usr/bin/python
from aux_fns import update_conda_env


def main():
    print("Running post-checkout hook script")

    update_conda_env()

    print("Finished post-checkout hook script")


if __name__ == "__main__":
    main()
